### ISSUE TITLE
Operation Joke-stealer

### ISSUE THREAD

**Issue by DonaldTsang** [wesbos/dad-jokes#184]
We steal the jokers of http://niceonedad.com/ (everything is stored in the `Text` object)

**Comment by wesbos** [comment]
These aren't programming related, but thanks :)

**Comment by DonaldTsang** [comment]
@wesbos well maybe the description should be clearer on "code-dad jokes" then.

**Comment by wesbos** [comment]
Its the first line of the readme

**Comment by DonaldTsang** [comment]
I meant the very brief description, not the ReadME...
