### ISSUE TITLE
Submit jokes through issues

### ISSUE THREAD

**Issue by optimizasean** [wesbos/dad-jokes#198]
To make it much easier to add jokes, I think they should be submitted through issues instead of pull requests.  This would prevent a lot of conflicts in pull requests and be much easier to add as individual commits and close.  I think for the purposes of this repository that would be a lot more streamlined and easier to go through and incorporate new ones.  Thoughts?

**Comment by jadeoye** [comment]
couldn't have agreed more 👌

**Comment by styfle** [comment]
I think that would be great, as long as the PR would give credit to the person who created the issue as the contributor 👍

**Comment by wesbos** [comment]
thanks for the issue but it's just a list of jokes and id like to keep it a list of jokes :)
