### ISSUE TITLE
How Does the Pirate-Coder use his variables before they're declared?

### ISSUE THREAD

**Issue by speckworks** [wesbos/dad-jokes#238]
VAAAAAAAAAR!!!

**Comment by styfle** [comment]
Its nearly identical to this existing joke:

> Q: How do programming pirates pass method parameters?
> 
> A: Varrrrarrrgs.

**Comment by speckworks** [comment]
Ok, thanks. Ulterior motive: I'm trying to find a humurous way to get devs
to stop using 'var' in our codebase.  Maybe I'm deranged.

**Comment by speckworks** [comment]
So to me its a joke about 'Var' and not about 'args'. So it's different.
