### ISSUE TITLE
`JSON` or `CSV` format?

### ISSUE THREAD

**Issue by dunhamjared** [wesbos/dad-jokes#45]
Would be nice if this was in a `JSON` or `CSV` format.

**Comment by wesbos** [comment]
There is a dad joke API already

https://icanhazdadjoke.com/api

If you want this to be formatted, just split on `---` 

Otherwise I don't want to make this a big thing 🤣

**Comment by DonaldTsang** [comment]
@wesbos at least make a converter that turns the ReadME into JSON or YAML when someone is offline.
