### ISSUE TITLE
Standard Liberal Moan

### ISSUE THREAD

**Issue by SecondeJK** [wesbos/dad-jokes#54]
While these amused me, a pet peeve of mine is kinda present:
Everyone in the gags are male for some reason.

**Comment by buttfedora** [comment]
> While these amused me, a pet peeve of mine is kinda present:
> Everyone in the gags are male for some reason.

"Dad jokes"

**Comment by SecondeJK** [comment]
"Dad jokes" doesn't mean the context of them all have to be blokes, because we're blokes and there are no female programmers... but I got more downvotes than positive so I guess we're still all bros.

**Comment by ibnuda** [comment]
you know, i down vote you because you present a problem without sending a patch where you can easily provide it.
be the change you want to see. lead with example. and standard stuff like that.

**Comment by SecondeJK** [comment]
That's a very fair point. I guess it didn't cross my mind as it's a bit fun police for something light hearted but yeah i might do a Pull-my-finger request

**Comment by SecondeJK** [comment]
#68

**Comment by wesbos** [comment]
:D thanks for this

**Comment by rfair404** [comment]
#174
